### ISSUE TITLE
speed doesn't work

### ISSUE THREAD

**Issue by inesgraphiste** [pixolin/scroll-to-anchor#4]
Hello, the plugin is really nice, but I have a problem with the speed of the scrolling, nothing changes if I set it to slow or fast. What can I do to make it work?
TIA
Inès

**Comment by pixolin** [comment]
Hello Inés,

I'm sorry for the late reply but was busy with other stuff and usually try to catch up with questions in the [plugin support forum](https://wordpress.org/support/plugin/scroll-to-anchor).
The plugin uses JavaScript for the animation. Conflicts with JavaScript of other plugins may cause the plugin animation not to work as desired. To debug this, I would need to get some more information about your website and the plugins and theme you use. Have you tried to disable all other plugins for debugging? Do the developer tools of your browser show any error messages in the console?
Best regards, Bego

**Comment by pixolin** [comment]
issue closed due to inactivity
