### ISSUE TITLE
Not working for me at all

### ISSUE THREAD

**Issue by x10sys** [pixolin/scroll-to-anchor#7]
As if I didn't install or activate the plugin.

I've tried with main menu links like `/page/#anchor` and just simply `#anchor` but no animation or offset is applied.

**Comment by pixolin** [comment]
Did you set the anchor first? Could you describe your workflow? 
Did you check for errors in the console of your browser's developer tools?
Does the error remain if you switch to a default theme and temporarily disable all plugins?

**Comment by x10sys** [comment]
Anchors placed properly (normal browser behaviour without smooth scroll).
No console errors.
I'm on a production site and cannot afford to switch themes or disable plugins :(

**Comment by pixolin** [comment]
Sorry, but without more information I won't be able to help you. 

Currently I don't even know, if you activated the plugin. Did you use the anchor-icon in the formatting tool bar of the post/page editor to place the shortcode? (I asked for your workflow, "anchors added properly" doesn't provide much information.) Is the shortcode rendered in the front page? Do you see the JavaScript in the source code of the rendered web page?

To test and try out new plugins, I recommend you set up a local web server as a development environment.

**Comment by x10sys** [comment]
Oh I see, i skipped part in documentation with visual editor and shortcodes... When I was reading the first time, I thought the plugin handles links by itself.

How to manually insert shortcode, since I'm not using visual editor (TinyMCE is not something I can afford to use since it rewrites my HTML code for my webapp)?

**Comment by pixolin** [comment]
The visual editor inserts a shortcode `[sta_anchor id="summary" /]` (or, if you encapsule text `[sta_anchor id="summary"]your text[/sta_anchor]`). The shortcode then gets rendered in frontend as  `<span id="summary" class="sta-anchor " aria-hidden="true"></span>`.  Either should work, but generally the idea was to provide an easy way to add anchors _with the formatting icon in TinyMCE_. If you don't use that, another plugin might even fit your needs better?

What HTML gets rewritten in TinyMCE? Sanitization of your code also could be a reason the plugin doesn't work as expected.

**Comment by x10sys** [comment]
This is perfect, thank you very much! I believe that will make your plugin functional for me.

That was the part I was missing in documentation. I completely agree with you to provide an easy access for inserting shortcodes through TinyMCE and for most people, that is the only way that they need.

My case was a bit complicated considering I'm forced to disable TinyMCE :)

Once more, thanks for this easy-to-use plugin. It's a good work!
