### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by coreyworrell** [pixolin/scroll-to-anchor#8]
Is there a reason that the anchor editor button is only shown when editing Posts and Pages? Ideally we would like to have it show for all post types.

`admin/sta-tinymce-button.php:16` limits it to just `array('post', 'page')`. This should probably use `apply_filters`. 

Thank you.

**Comment by scharc** [comment]
+1 
Maybe make the posttypes selectable in the setting page?
